source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "faker", "~> 3.4", ">= 3.4.2"

# Postgresql
gem "pg", "~> 1.1"

# puma
gem "puma", "~> 5.0"

# rails本体（標準gem）
gem "rack-cors"
gem "rails", "~> 7.0.4"

# Japanese
gem "rails-i18n"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # pry コンソール
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # rspec
  gem "rspec-rails"

  # rubocop
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"

  gem "graphiql-rails"
  gem "sass-rails"
end

gem "graphql", "~> 2.3"
gem "secure_headers"
