source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# Postgresql
gem "pg", "~> 1.1"

# puma
gem "puma", "~> 5.0"

# rails本体（標準gem）
gem "rails", "~> 7.0.4"
gem "rack-cors"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # pry コンソール
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # rspec
  gem "rspec-rails"

  # rubocop
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

gem "graphql", "~> 2.3"
